version: '2'
services:
  redis1:
    image: redis
    ports:
      - "63791:6379"
  redis2:
    image: redis
    ports:
      - "63792:6379"
  redis3:
    image: redis
    ports:
      - "63793:6379"
  redis4:
    image: redis
    ports:
      - "63794:6379"
  redis5:
      image: redis
      ports:
        - "63795:6379"

  mongo1:
    image: mongo:3.3
    ports:
      - "27011:27017"
    command: mongod --smallfiles --replSet rs

  mongo2:
    image: mongo:3.3
    ports:
      - "27012:27017"
    command: mongod --smallfiles --replSet rs

  mongo3:
    image: mongo:3.3
    ports:
      - "27013:27017"
    command: mongod --smallfiles --replSet rs

  mongo4:
    image: mongo:3.3
    ports:
      - "27014:27017"
    command: mongod --smallfiles --replSet rs

  mongo5:
    image: mongo:3.3
    ports:
      - "27015:27017"
    command: mongod --smallfiles --replSet rs



  nginx:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-nginx
    ports:
      - "80:80"
      - "433:433"

    links:
      - server1:server1
      - server2:server2
      - server3:server3

    depends_on:
      - server1
      - server2
      - server3

  server1:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-node
    ports:
      - "3000:3000"
    links:
      - redis1:redis1
      - redis2:redis2
      - redis3:redis3
      - redis4:redis4
      - redis5:redis5
      - mongo1:mongo1
      - mongo2:mongo2
      - mongo3:mongo3
      - mongo4:mongo4
      - mongo5:mongo5
    depends_on:
      - redis1
      - redis2
      - redis3
      - redis4
      - redis5
      - mongo1
      - mongo2
      - mongo3
      - mongo4
      - mongo5


  server2:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-node
    ports:
      - "3001:3000"
    links:
      - redis1:redis1
      - redis2:redis2
      - redis3:redis3
      - redis4:redis4
      - redis5:redis5
      - mongo1:mongo1
      - mongo2:mongo2
      - mongo3:mongo3
      - mongo4:mongo4
      - mongo5:mongo5
    depends_on:
      - redis1
      - redis2
      - redis3
      - redis4
      - redis5
      - mongo1
      - mongo2
      - mongo3
      - mongo4
      - mongo5



  server3:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-node
    ports:
      - "3002:3000"
    links:
      - redis1:redis1
      - redis2:redis2
      - redis3:redis3
      - redis4:redis4
      - redis5:redis5
      - mongo1:mongo1
      - mongo2:mongo2
      - mongo3:mongo3
      - mongo4:mongo4
      - mongo5:mongo5
    depends_on:
      - redis1
      - redis2
      - redis3
      - redis4
      - redis5
      - mongo1
      - mongo2
      - mongo3
      - mongo4
      - mongo5
